package com.dreamless.brewery.brew;

import org.bukkit.Material;

public enum Aspect {
	LITHIC, INFERNAL, PYROTIC, AERIAL, VOID, AQUATIC, INVALID;
	
	public static Aspect getAspect(Material material) {
		switch(material) {
		case OAK_SAPLING:
		case OAK_LEAVES:
		case DANDELION:
		case ALLIUM:
		case ORANGE_TULIP:
		case ROSE_BUSH:
		case PEONY:
		case BROWN_MUSHROOM:
		case RED_MUSHROOM:
		case VINE:
		case BEACON:
		case SLIME_BALL:
		case SLIME_BLOCK:
		case APPLE:
		case FEATHER:
		case RABBIT_FOOT:
		case HONEYCOMB:
		case HONEY_BLOCK:
		case TALL_GRASS:
			return AERIAL;
		case SPRUCE_SAPLING:
		case SPRUCE_LEAVES:
		case SPONGE:
		case BLUE_ORCHID:
		case AZURE_BLUET:
		case LILAC:
		case SNOWBALL:
		case MELON_SLICE:
		case MELON:
		case LILY_PAD:
		case NAUTILUS_SHELL:
		case PRISMARINE_SHARD:
		case PRISMARINE_CRYSTALS:
		case COD:
		case SALMON:
		case TROPICAL_FISH:
		case COOKED_COD:
		case COOKED_SALMON:
		case HONEY_BOTTLE:
		case MILK_BUCKET:
		case KELP:
		case TALL_SEAGRASS:
			return AQUATIC;
		case JUNGLE_SAPLING:
		case JUNGLE_LEAVES:
		case COBWEB:
		case GOLD_NUGGET:
		case GOLD_INGOT:
		case GOLD_BLOCK:
		case QUARTZ:
		case QUARTZ_BLOCK:
		case GLOWSTONE_DUST:
		case GLOWSTONE:
		case NETHERRACK:
		case SOUL_SAND:
		case NETHER_WART:
		case NETHER_STAR:
		case GOLDEN_APPLE:
		case GHAST_TEAR:
		case ROTTEN_FLESH:
		case SPIDER_EYE:
		case FERMENTED_SPIDER_EYE:
		case POISONOUS_POTATO:
		case GOLDEN_CARROT:
			return INFERNAL;
		case BIRCH_SAPLING:
		case BIRCH_LEAVES:
		case SAND:
		case GRAVEL:
		case IRON_NUGGET:
		case IRON_INGOT:
		case IRON_BLOCK:
		case DIAMOND:
		case DIAMOND_BLOCK:
		case EMERALD:
		case EMERALD_BLOCK:
		case COCOA_BEANS:
		case CARROTS:
		case POTATOES:
		case BEETROOTS:
		case WHEAT:
		case BREAD:
		case HAY_BLOCK:
		case BONE:
		case BONE_BLOCK:
		case STICK:
		case LAPIS_LAZULI:
			return LITHIC;
		case ACACIA_SAPLING:
		case COAL:
		case CHARCOAL:
		case ACACIA_LEAVES:
		case GLASS:
		case DEAD_BUSH:
		case POPPY:
		case RED_TULIP:
		case SUNFLOWER:
		case OBSIDIAN:
		case PUMPKIN:
		case PUMPKIN_SEEDS:
		case MAGMA_CREAM:
		case MAGMA_BLOCK:
		case GUNPOWDER:
		case PORKCHOP:
		case COOKED_PORKCHOP:
		case BLAZE_ROD:
		case BLAZE_POWDER:
		case GLISTERING_MELON_SLICE:
			return PYROTIC;
		case DARK_OAK_SAPLING:
		case DARK_OAK_LEAVES:
		case FERN:
		case WHITE_TULIP:
		case PINK_TULIP:
		case OXEYE_DAISY:
		case LARGE_FERN:
		case REDSTONE:
		case SUGAR:
		case CACTUS:
		case DRAGON_EGG:
		case CHORUS_FRUIT:
		case POPPED_CHORUS_FRUIT:
		case CHORUS_FLOWER:
		case END_ROD:
		case PURPUR_BLOCK:
		case SHULKER_SHELL:
		case EGG:
		case ENDER_PEARL:
		case DRAGON_BREATH:
		case WITHER_ROSE:
			return VOID;
		default:
			return INVALID;
		}
	}
	
	public static Aspect getFilterAspect(Material material) {
		switch(material) {
		case DIORITE:
			return AERIAL;
		case GRANITE:
			return LITHIC;
		case ANDESITE:
			return INFERNAL;
		case GRAVEL:
			return PYROTIC;
		case SAND:
			return AQUATIC;
		case COBBLESTONE:
			return VOID;
		default:
			return INVALID;
		}
	}
}
